# DesignBench antibody (Fab) target 06_5VLI
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/06_5VLI.cif
      include:
            - chain:
                id: B
  - file:
        path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/hu-4D5-8_Fv.yaml
