# DesignBench antibody (Fab) target 09_4G8A
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/09_4G8A.cif
      include:
            - chain:
                id: A
            - chain:
                id: B
  - file:
        path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/hu-4D5-8_Fv.yaml
