# DesignBench antibody (Fab) target 10_6X93
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/10_6X93.cif
      include:
            - chain:
                id: A
  - file:
        path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/hu-4D5-8_Fv.yaml
