# DesignBench antibody (Fab) target 11_4ZAM
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/11_4ZAM.cif
      include:
            - chain:
                id: A
  - file:
        path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/hu-4D5-8_Fv.yaml
