# DesignBench antibody (Fab) target 20_1P4M
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/20_1NB0.cif
      include:
            - chain:
                id: A
  - file:
        path:
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/adalimumab.6cr1.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/belimumab.5y9k.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/dupilumab.6wgb.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/golimumab.5yoy.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/guselkumab.4m6m.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/nirsevimab.5udc.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/sarilumab.8iow.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/secukinumab.6wio.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/tezepelumab.5j13.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/tralokinumab.5l6y.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/ustekinumab.3hmw.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/mab1.3h42.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/necitumumab.6b3s.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/antibody/crenezumab.5vzy.yaml
