# BenchCore antibody (Fab) target 21_6COB
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/benchcore/assets/antibody_nanobody/antigens/21_6C0B.cif
      include:
            - chain:
                id: A
  - file:
        path: /home/qiantai/zihan/benchcore/assets/antibody_nanobody/scaffolds/antibody/hu-4D5-8_Fv.yaml
