# BenchCore nanobody target 01_7UXQ
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/benchcore/assets/antibody_nanobody/antigens/01_7UXQ.cif
      include:
            - chain:
                id: A
  - file:
        path: /home/qiantai/zihan/benchcore/assets/antibody_nanobody/scaffolds/nanobody/h-NbBCII10.yaml
