# BenchCore nanobody target 03_3MJG
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/benchcore/assets/antibody_nanobody/antigens/03_3MJG.cif
      include:
            - chain:
                id: C
  - file:
        path: /home/qiantai/zihan/benchcore/assets/antibody_nanobody/scaffolds/nanobody/h-NbBCII10.yaml
