# DesignBench nanobody target 04_3DI3
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/04_3DI3.cif
      include:
            - chain:
                id: B
  - file:
        path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/h-NbBCII10.yaml
