# DesignBench nanobody target 15_1I9A
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/15_2PNY.cif
      include:
            - chain:
                id: A
  - file:
        path:
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/7eow.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/7xl0.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/8coh.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/8z8v.yaml
