# DesignBench nanobody target 20_1P4M
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/20_1NB0.cif
      include:
            - chain:
                id: A
  - file:
        path:
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/7eow.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/7xl0.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/8coh.yaml
            - /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/8z8v.yaml
