# DesignBench nanobody target 21_6COB
# Generated for BoltzGen; 100 designs per target.
entities:
  - file:
      path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/antigens/21_6C0B.cif
      include:
            - chain:
                id: A
  - file:
        path: /home/qiantai/zihan/designbench/assets/antibody_nanobody/scaffolds/nanobody/h-NbBCII10.yaml
